### ISSUE TITLE
Wrong spaces in the description...

### ISSUE THREAD

**Issue by lochmueller** [johngrogg/ics-parser#37]
Hey folks,

the description is trimmed wrong. I got this ICS from google calendar.
![example](https://cloud.githubusercontent.com/assets/3907126/10083928/fb870fb4-6300-11e5-83f8-3cf3f3d9a033.png)

The lines have a leading space, that is NOT part of the description. But the space on the right side (i mark the space in the first line) is part of the description. So it is wrong to trim the right space. I remove the rtrim in the "initLines" function, to get the right description.

Wrong thought?

Regards,
Tim

**Comment by u01jmg3** [comment]
I'm struggling to understand your issue

Do you mean you think there should be a trailing space on the second line, rather than a leading space on the third line, when the description is parsed? If so, there will be no difference in output unless I have missed something.

As per our [contribution guide](https://github.com/johngrogg/ics-parser/blob/master/CONTRIBUTING.md) it is recommended to supply a snippet of the problematic iCal file so on our end we can reproduce the problem in order to fix any issues

**Comment by lochmueller** [comment]
Thanks for your feedback. The space in the beginning is a "structure space" this space have to be removed. If not, the result is something like "b reakfast" (2.+3. line), but the result should be "breakfast". But if the string is trimmed on both sides, the result is "yearbegins" (1.+2. line), but the result should be "year begins".

As result... the description should concat with a "ltrim" and no "rtrim"?!?!

Regards,
Tim

**Comment by lochmueller** [comment]
If you confirm, I will fork the repo and pull request the change. But the question is... remove the "rtrim" or replace it with "ltrim". I don't really know, why there is a rtrim?

**Comment by u01jmg3** [comment]
Hold the PR

If you give me an iCal snippet to work with I can investigate further

`rtrim` is purposely used; there are cases when `ltrim` removes leading spaces that are required so swapping to use it is not the solution

**Comment by u01jmg3** [comment]
Closing as no snippet provided to properly investigate this issue; will happily re-open
